# West manifest file for UWB Tag Firmware
manifest:
  self:
    path: uwb-tag-firmware

  remotes:
    - name: nrfconnect
      url-base: https://github.com/nrfconnect

  projects:
    - name: sdk-nrf
      remote: nrfconnect
      revision: v2.6.0
      import: true
